[package]
name = "reducer"
version = "1.1.0"
edition = "2021"
authors = ["Maskedball <maskedballmail@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
exitcode = "1.1.2"
image = "0.24.5"
webp = "0.2"
